# Generated by Django 4.0.4 on 2022-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('card_number', models.IntegerField(null=True)),
                ('cvv', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('delivery_status', models.BooleanField(default=False, null=True)),
                ('payment_status', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
