# Generated by Django 4.0.4 on 2022-05-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0003_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_cakemaker',
            new_name='is_maker',
        ),
        migrations.DeleteModel(
            name='supplier',
        ),
    ]
